# Generated by Django 3.0.3 on 2020-02-25 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iftar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mosque',
            name='donor_menu_button',
            field=models.CharField(default='one', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mosque',
            name='donor_page_title',
            field=models.CharField(default='two', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mosque',
            name='schedule_menu_button',
            field=models.CharField(default='menu1', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mosque',
            name='schedule_page_title',
            field=models.CharField(default='menu2', max_length=100),
            preserve_default=False,
        ),
    ]
